<?php
/**
 * InlineResponse2004DataAnalytics
 *
 * PHP version 5
 *
 * @category Class
 * @package  ListcleanSwagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Listclean API (Beta)
 *
 * Listclean APIs. For API reference doc at [https://api.listclean.xyz](https://api.listclean.xyz).
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@listclean.xyz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ListcleanSwagger\Client\Model;

use \ArrayAccess;
use \ListcleanSwagger\Client\ObjectSerializer;

/**
 * InlineResponse2004DataAnalytics Class Doc Comment
 *
 * @category Class
 * @package  ListcleanSwagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2004DataAnalytics implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_4_data_analytics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'summary' => '\ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsSummary',
        'dirty_summary' => '\ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsDirtySummary[]',
        'clean_summary' => '\ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsCleanSummary[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'summary' => null,
        'dirty_summary' => null,
        'clean_summary' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'summary' => 'summary',
        'dirty_summary' => 'dirty_summary',
        'clean_summary' => 'clean_summary'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'summary' => 'setSummary',
        'dirty_summary' => 'setDirtySummary',
        'clean_summary' => 'setCleanSummary'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'summary' => 'getSummary',
        'dirty_summary' => 'getDirtySummary',
        'clean_summary' => 'getCleanSummary'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['summary'] = isset($data['summary']) ? $data['summary'] : null;
        $this->container['dirty_summary'] = isset($data['dirty_summary']) ? $data['dirty_summary'] : null;
        $this->container['clean_summary'] = isset($data['clean_summary']) ? $data['clean_summary'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets summary
     *
     * @return \ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsSummary
     */
    public function getSummary()
    {
        return $this->container['summary'];
    }

    /**
     * Sets summary
     *
     * @param \ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsSummary $summary summary
     *
     * @return $this
     */
    public function setSummary($summary)
    {
        $this->container['summary'] = $summary;

        return $this;
    }

    /**
     * Gets dirty_summary
     *
     * @return \ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsDirtySummary[]
     */
    public function getDirtySummary()
    {
        return $this->container['dirty_summary'];
    }

    /**
     * Sets dirty_summary
     *
     * @param \ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsDirtySummary[] $dirty_summary dirty_summary
     *
     * @return $this
     */
    public function setDirtySummary($dirty_summary)
    {
        $this->container['dirty_summary'] = $dirty_summary;

        return $this;
    }

    /**
     * Gets clean_summary
     *
     * @return \ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsCleanSummary[]
     */
    public function getCleanSummary()
    {
        return $this->container['clean_summary'];
    }

    /**
     * Sets clean_summary
     *
     * @param \ListcleanSwagger\Client\Model\InlineResponse2004DataAnalyticsCleanSummary[] $clean_summary clean_summary
     *
     * @return $this
     */
    public function setCleanSummary($clean_summary)
    {
        $this->container['clean_summary'] = $clean_summary;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


