<?php
/**
 * BodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ListcleanSwagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Listclean API (Beta)
 *
 * Listclean APIs. For API reference doc at [https://api.listclean.xyz](https://api.listclean.xyz).
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@listclean.xyz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ListcleanSwagger\Client;

/**
 * BodyTest Class Doc Comment
 *
 * @category    Class
 * @description Body
 * @package     ListcleanSwagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BodyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body"
     */
    public function testBody()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "file_type"
     */
    public function testPropertyFileType()
    {
    }

    /**
     * Test attribute "total_chunk_count"
     */
    public function testPropertyTotalChunkCount()
    {
    }

    /**
     * Test attribute "max_chunk_size"
     */
    public function testPropertyMaxChunkSize()
    {
    }
}
