<?php
/**
 * ListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ListcleanSwagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Listclean API (Beta)
 *
 * Listclean APIs. For API reference doc at [https://api.listclean.xyz](https://api.listclean.xyz).
 *
 * OpenAPI spec version: 0.1.0
 * Contact: support@listclean.xyz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ListcleanSwagger\Client;

use \ListcleanSwagger\Client\Configuration;
use \ListcleanSwagger\Client\ApiException;
use \ListcleanSwagger\Client\ObjectSerializer;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ListcleanSwagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for listsGet
     *
     * Get the all list info.
     *
     */
    public function testListsGet()
    {
    }

    /**
     * Test case for listsListIdDelete
     *
     * Delete the single list.
     *
     */
    public function testListsListIdDelete()
    {
    }

    /**
     * Test case for listsListIdGet
     *
     * Get the single list info.
     *
     */
    public function testListsListIdGet()
    {
    }
}
